export const STAR_WARS_APP_FILMS_LOADING = "STAR_WARS_APP_FILMS_LOADING";
export const STAR_WARS_APP_FILMS_LOADED = "STAR_WARS_APP_FILMS_LOADED";
export const STAR_WARS_APP_FILMS_RESET="STAR_WARS_APP_FILMS_RESET";
export const STAR_WARS_APP_FILMS_SELECT="STAR_WARS_APP_FILMS_SELECT";
